// <auto-generated />
using System;
using MCN.ServiceRep.BAL.ContextModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MCN.ServiceRep.BAL.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20220327024201_timeslot")]
    partial class timeslot
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MCN.Core.Entities.Entities.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoginFailureCount")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserLoginTypeId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MCN.Core.Entities.Entities.UserLoginType", b =>
                {
                    b.Property<int>("UserLoginTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserLoginName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserLoginTypeId");

                    b.ToTable("UserLoginType");
                });

            modelBuilder.Entity("MCN.Core.Entities.Entities.UserMultiFactor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccessIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("UserMultiFactors");
                });

            modelBuilder.Entity("MCN.Core.Entities.Entities.appointment.Appointment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Appointment");
                });

            modelBuilder.Entity("MCN.Core.Entities.Entities.appointment.DoctorSpecialist", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int?>("SpecialistId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DoctorId");

                    b.HasIndex("SpecialistId");

                    b.ToTable("DoctorSpecialist");
                });

            modelBuilder.Entity("MCN.Core.Entities.Entities.appointment.Specialist", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Specialist");
                });

            modelBuilder.Entity("MCN.Core.Entities.Entities.appointment.TimeSlot", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<bool?>("Slot1")
                        .HasColumnType("bit");

                    b.Property<bool?>("Slot10")
                        .HasColumnType("bit");

                    b.Property<bool?>("Slot11")
                        .HasColumnType("bit");

                    b.Property<bool?>("Slot12")
                        .HasColumnType("bit");

                    b.Property<bool?>("Slot2")
                        .HasColumnType("bit");

                    b.Property<bool?>("Slot3")
                        .HasColumnType("bit");

                    b.Property<bool?>("Slot4")
                        .HasColumnType("bit");

                    b.Property<bool?>("Slot5")
                        .HasColumnType("bit");

                    b.Property<bool?>("Slot6")
                        .HasColumnType("bit");

                    b.Property<bool?>("Slot7")
                        .HasColumnType("bit");

                    b.Property<bool?>("Slot8")
                        .HasColumnType("bit");

                    b.Property<bool?>("Slot9")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("TimeSlot");
                });

            modelBuilder.Entity("MCN.Core.Entities.Entities.UserMultiFactor", b =>
                {
                    b.HasOne("MCN.Core.Entities.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MCN.Core.Entities.Entities.appointment.DoctorSpecialist", b =>
                {
                    b.HasOne("MCN.Core.Entities.Entities.User", "Users")
                        .WithMany()
                        .HasForeignKey("DoctorId");

                    b.HasOne("MCN.Core.Entities.Entities.appointment.Specialist", "Specialist")
                        .WithMany()
                        .HasForeignKey("SpecialistId");
                });
#pragma warning restore 612, 618
        }
    }
}
